# -*- coding: utf-8 -*-
"""python_basics_chandrababu.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvFwVx9SBTD7QeqQv6pVyAc1pySJDulO
"""

name = "chandrababu"
age = 35
height = 1.75
is_student = False
print(name, age, height, is_student)

print(f"Name : {name} | Age : {age} | Height : {height} | student : {is_student}")

print("Age in months :", age*12)
print("Age in days :", age*365)
print("Remainder when age is devided by 7:", age%7)
print("Age raised to the poewer of 2 :", age**2)